### ISSUE TITLE
Proxy should be able to make use of the existing CPU resources without any setting

### ISSUE THREAD

**Issue by franz1981** [kroxylicious/kproxy#15]
Netty allows to specify the number of event loop threads in the event loop group: it would be nice if the number of available cores will be used to set it, if the user hasn't specified anything different.

In addition, it would be nice to use a separate acceptor (group of) thread(s) for incoming connections, to not bother the existing selector(s) in the other threads with accept events.

**Comment by gunnarmorling** [comment]
@franz1981, I think that's done, right?

**Comment by franz1981** [comment]
Right, given that was a one liner, I have embedded it into my last change re io_uring.
I believe we can expose the balance of threads used to manage accepting connections vs handling connection traffic, but it's a separate thing
