### ISSUE TITLE
Adjust license header

### ISSUE THREAD

**Issue by gunnarmorling** [kroxylicious/kproxy#47]
In the currently used file header, it says:

> Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.

Which isn't true; neither do we license exclusively to the ASF, nor do we have a CLA (nor do we want one). My suggestion is to use a condensed form for the header, similar to how it's done in Debezium:

```
/*
 * Copyright Kroxylicious Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
```

**Comment by gunnarmorling** [comment]
@tombentley, any thoughts/concerns?

**Comment by tombentley** [comment]
SGTM

**Comment by gunnarmorling** [comment]
SGTM = "Seems good to me"?

**Comment by tombentley** [comment]
Sounds good to me.

**Comment by gunnarmorling** [comment]
Aaah, makes sense. I only know LGTM ("Looks..."). TIL :)
