### ISSUE TITLE
Break up circular package dependencies

### ISSUE THREAD

**Issue by gunnarmorling** [kroxylicious/kproxy#60]
Spend some time setting up [Deptective](https://github.com/moditect/deptective/) for Kroxylicious, in order to understand its current package dependencies. Turns out there's some cycles which we probably should try to get rid of sooner than later:

![kroxylicious-arch](https://user-images.githubusercontent.com/28612/174766592-9368fc47-4347-4ac7-be2b-ecfc436e355b.png)

**Comment by gunnarmorling** [comment]
// CC @tombentley

**Comment by tombentley** [comment]
We might be able to take `encode` out of `Frame` and put it in `KafkaMessageEncoder`, but we'd need to expose the fields of those frames.
