### ISSUE TITLE
Establish CI/CD pipeline with GitHub Actions

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kproxy#73]
The project should setup a CI/CD pipeline based on GitHub Actions.

**Comment by gunnarmorling** [comment]
There's this one already: https://github.com/kroxylicious/kproxy/blob/main/.github/workflows/maven.yml. Is there any specific flows you'd like to add?

**Comment by k-wall** [comment]
somehow I failed to see it, thank you.
